export const FEED_FETCH_REQUESTED = "FEED_FETCH_REQUESTED";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_PAGE = "SET_PAGE";
export const SET_TOTAL_CATEGORIES_COUNT = "SET_TOTAL_CATEGORIES_COUNT";
export const CATEGORY_PAGE_CHANGED = "CATEGORY_PAGE_CHANGED";
export const SET_CURRENT_CATEGORIES_PAGE = "SET_CURRENT_CATEGORIES_PAGE";
export const SET_CURRENT_CATEGORIES_ARRAY = "SET_CURRENT_CATEGORIES_ARRAY";
export const ADD_FEED = "ADD_FEED";
export const ADD_FEED_TO_USER_LIST = "ADD_FEED_TO_USER_LIST";



